title: ResumeLink
description: Human-Centric AI Career Guides 2026
url: "https://resumelink.cc"

collections:
  roles:
    output: true
    permalink: /roles/:name/

# Принудительно заставляем Jekyll зайти в эту папку
include: [_roles]

defaults:
  - scope:
      path: ""
      type: "roles"
    values:
      layout: "role"
