title: ResumeLink
url: "https://resumelink.cc"
baseurl: ""

plugins:
  - jekyll-sitemap

collections:
  roles:
    output: true
    permalink: /roles/:name/

defaults:
  - scope:
      path: ""
      type: "roles"
    values:
      layout: "role"

permalink: /:path/
